// <auto-generated />
using System;
using Chitter.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chitter.Migrations
{
    [DbContext(typeof(ChitterDbContext))]
    [Migration("20250418011743_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chitter.Models.ChitPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChitPostId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChitPostId");

                    b.HasIndex("UserId");

                    b.ToTable("ChitPosts");
                });

            modelBuilder.Entity("Chitter.Models.ChitPostComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChitPostId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChitPostId");

                    b.HasIndex("UserId");

                    b.ToTable("ChitPostComments");
                });

            modelBuilder.Entity("Chitter.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Chitter.Models.ChitPost", b =>
                {
                    b.HasOne("Chitter.Models.ChitPost", null)
                        .WithMany("ChitPosts")
                        .HasForeignKey("ChitPostId");

                    b.HasOne("Chitter.Models.User", "User")
                        .WithMany("ChitPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chitter.Models.ChitPostComment", b =>
                {
                    b.HasOne("Chitter.Models.ChitPost", null)
                        .WithMany("ChitPostComments")
                        .HasForeignKey("ChitPostId");

                    b.HasOne("Chitter.Models.User", null)
                        .WithMany("ChitPostComments")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Chitter.Models.ChitPost", b =>
                {
                    b.Navigation("ChitPostComments");

                    b.Navigation("ChitPosts");
                });

            modelBuilder.Entity("Chitter.Models.User", b =>
                {
                    b.Navigation("ChitPostComments");

                    b.Navigation("ChitPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
